services:
  # A web service
  - type: web
    name: petradar-api
    env: python
    buildCommand: curl -sSL https://install.python-poetry.org | python3 - --version 2.1.2 && ~/.local/bin/poetry config virtualenvs.create false && ~/.local/bin/poetry install --no-dev
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: APP_NAME
        value: PetRadar
      - key: DATABASE_URL
        sync: false 
      - key: SECRET_KEY
        generateValue: true
      - key: STORAGE_PROVIDER
        value: local
      - key: UPLOAD_DIR
        value: ./uploads
