"""user update

Revision ID: 3579eddd8ab3
Revises: 75df59778d30
Create Date: 2025-04-09 13:15:08.212334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3579eddd8ab3'
down_revision: Union[str, None] = '75df59778d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
